import type { Metadata } from "next";
import { Open_Sans, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { Providers } from "./components/theme-provider";

const openSans = Open_Sans({
  variable: "--font-openSans",
  subsets: ["latin"],
});
const roboto = Roboto_Condensed({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${openSans.variable} ${roboto.variable} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
